### ISSUE TITLE
No minions matched the target. No command was sent, no jid was assigned.

### ISSUE THREAD

**Issue by oviliz** [0x4D31/salt-scanner#1]
```
root@localhost:~/Tools/salt-scanner# python -V; pip freeze|grep salt; pip freeze|grep slackclient
Python 2.7.12
root@localhost:~/Tools/salt-scanner# pip uninstall salt
root@localhost:~/Tools/salt-scanner# python -V; pip freeze|grep salt; pip freeze|grep slackclient
Python 2.7.12
salt==2016.11.5
root@localhost:~/Tools/salt-scanner# pip install slackclient
root@localhost:~/Tools/salt-scanner# python -V; pip freeze|grep salt; pip freeze|grep slackclient
Python 2.7.12
salt==2016.11.5
slackclient==1.0.6
root@localhost:~/Tools/salt-scanner# SLACK_API_TOKEN="MYTOKEN" python salt-scanner.py

 ==========================================================
 _____       _ _     _____
/  ___|     | | |   /  ___|
\ `--.  __ _| | |_  \ `--.  ___ __ _ _ __  _ __   ___ _ __
 `--. \/ _` | | __|  `--. \/ __/ _` | '_ \| '_ \ / _ \ '__|
/\__/ / (_| | | |_  /\__/ / (_| (_| | | | | | | |  __/ |
\____/ \__,_|_|\__| \____/ \___\__,_|_| |_|_| |_|\___|_|

 Vulnerability scanner based on Vulners API and Salt Open
===========================================================

+ No default OS is configured. Detecting OS...
Traceback (most recent call last):
  File "salt-scanner.py", line 325, in <module>
    main()
  File "salt-scanner.py", line 311, in main
    os_dict = get_os(hosts_list)
  File "salt-scanner.py", line 64, in get_os
    client = salt.client.LocalClient()
  File "/usr/local/lib/python2.7/dist-packages/salt/client/__init__.py", line 160, in __init__
    self.key = self.__read_master_key()
  File "/usr/local/lib/python2.7/dist-packages/salt/client/__init__.py", line 193, in __read_master_key
    self.skip_perm_errors)
  File "/usr/local/lib/python2.7/dist-packages/salt/utils/verify.py", line 400, in check_path_traversal
    raise SaltClientError(msg)
salt.exceptions.SaltClientError: Could not access /var/cache/salt. Path does not exist.
root@localhost:~/Tools/salt-scanner# apt update && apt install salt-api salt-cloud salt-common salt-doc salt-master salt-minion salt-proxy salt-ssh salt-syndic -y
root@localhost:~/Tools/salt-scanner# SLACK_API_TOKEN="MYTOKEN" python salt-scanner.py

 ==========================================================
 _____       _ _     _____
/  ___|     | | |   /  ___|
\ `--.  __ _| | |_  \ `--.  ___ __ _ _ __  _ __   ___ _ __
 `--. \/ _` | | __|  `--. \/ __/ _` | '_ \| '_ \ / _ \ '__|
/\__/ / (_| | | |_  /\__/ / (_| (_| | | | | | | |  __/ |
\____/ \__,_|_|\__| \____/ \___\__,_|_| |_|_| |_|\___|_|

 Vulnerability scanner based on Vulners API and Salt Open
===========================================================

+ No default OS is configured. Detecting OS...
No minions matched the target. No command was sent, no jid was assigned.
root@localhost:~/Tools/salt-scanner# echo "OK, I give up"
```

**Comment by 0x4D31** [comment]
Could you please run the following command on your salt-master and see if it returns the result? Seems the minions aren't connected to salt-master!
`salt '*' test.ping`

**Comment by 0x4D31** [comment]
> root@localhost:~/Tools/salt-scanner# apt update && apt install salt-api salt-cloud salt-common salt-doc salt-master salt-minion salt-proxy salt-ssh salt-syndic -y
@oviliz Ahh, Just noticed that you've just installed salt-master/minion! Do you use SaltStack in your infrastructure at all? Please have a look at https://docs.saltstack.com/en/latest/topics/tutorials/walkthrough.html

**Comment by oviliz** [comment]
No, I don't but now I've got your idea.
Looking forward to your Documentation. Thank you.
