### ISSUE TITLE
Salt Scanner Payment required 

### ISSUE THREAD

**Issue by SudeepParajuli** [0x4D31/salt-scanner#6]
We are researching the feasibility of using salt scanner cli for scanning debian package in our remote server. While running the salt scanner cli after configuring the salt master and minions  we are getting the following message about payment from vulners api . Any suggestion is highly appreciated . 
```

 ==========================================================
  Vulnerability scanner based on Vulners API and Salt Open
 _____       _ _     _____                                 
/  ___|     | | |   /  ___|                               
\ `--.  __ _| | |_  \ `--.  ___ __ _ _ __  _ __   ___ _ __ 
 `--. \/ _` | | __|  `--. \/ __/ _` | '_ \| '_ \ / _ \ '__|
/\__/ / (_| | | |_  /\__/ / (_| (_| | | | | | | |  __/ |   
\____/ \__,_|_|\__| \____/ \___\__,_|_| |_|_| |_|\___|_|   

               Salt-Scanner 0.1 / by 0x4D31               
 ==========================================================


+ No default OS is configured. Detecting OS...
+ Detected Operating Systems:
   - OS Name: ubuntu, OS Version: 16.04
+ Getting the Installed Packages...
+ Started Scanning '1.2.3.4'...
   - Total Packages: 647
https://vulners.com/api/v3/audit/audit/
Traceback (most recent call last):
  File "./salt-scanner.py", line 571, in <module>
    main()
  File "./salt-scanner.py", line 563, in main
    args.target_hosts
  File "./salt-scanner.py", line 204, in audit
    response = sendVulnRequest(url, payload)
  File "./salt-scanner.py", line 157, in sendVulnRequest
    response = urllib2.urlopen(req, json.dumps(payload).encode('utf-8'))
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 402: Payment Required
```

**Comment by oviliz** [comment]
This repo hasn't had any update for 2.5 years now and the author hasn't since responded to opened issues. I'm afraid this is a dead project.

**Comment by 0x4D31** [comment]
Yeah apparently vulners api has been changed. Should be easy to fix it but this is just an old / couple-day project and I don’t maintain it anymore. Going to archive it.
